// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRsymmCmmjvDcSAOjm_EuCU-VCfoCMTQ4',
    appId: '1:1059982709719:web:59b11325a8314af5f43192',
    messagingSenderId: '1059982709719',
    projectId: 'flutter-firebase-auth-43532',
    authDomain: 'flutter-firebase-auth-43532.firebaseapp.com',
    storageBucket: 'flutter-firebase-auth-43532.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfabGk6jXWmRvls46FBU370fNfHp09ZSY',
    appId: '1:1059982709719:android:f72d068347db4e49f43192',
    messagingSenderId: '1059982709719',
    projectId: 'flutter-firebase-auth-43532',
    storageBucket: 'flutter-firebase-auth-43532.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqixDnxu8dY6gjsP5nFV7cdTBMCt63c9Q',
    appId: '1:1059982709719:ios:f014989668163f22f43192',
    messagingSenderId: '1059982709719',
    projectId: 'flutter-firebase-auth-43532',
    storageBucket: 'flutter-firebase-auth-43532.appspot.com',
    iosClientId: '1059982709719-jjbkkok2s7c9tsvia58na4tce4120hcp.apps.googleusercontent.com',
    iosBundleId: 'app.devrodolfo.flutterFirebaseAuth',
  );
}
